gesdinet_jwt_refresh_token:
    ttl: '%env(int:REFRESH_TTL)%'
    ttl_update: true
    user_identity_field: email
    user_provider: security.user.provider.concrete.app_user_provider
    single_use: true